print("My name is Stanslaus")
print("I am 18 years old")
print("I come from Nairobi County")
print("I love acting, dancing, watching")
print("---------------")
print("****************")
print("###############")